CSI-1190: Fix Retry device upgrade when check latest firmware fails
Cypherock/cysync-desktop pull request #161
Opened 2022-07-30 13:44 UTC by irshadCypherock

2022-07-30 13:45 UTC, irshadCypherock commented
Task linked: [CSI-1190 BugFix: Retry device upgrade when check latest firmware fails](https://app.clickup.com/t/37308523/CSI-1190)

2022-08-03 06:57 UTC, HarishRocks requested changes

2022-08-03 06:57 UTC, HarishRocks commented on cysync/src/pages/mainApp/notification/notificationItem.tsx
> +      navigate(`${Routes.settings.device.upgrade}?isRefresh=true`);
check if there is internet before navigating here

2022-08-04 11:50 UTC, HarishRocks approved these changes

2022-08-04 13:23 UTC, merged