CSI-1191: Don't retry when device upgrade is successful but device au…
Cypherock/cysync-desktop pull request #162
Opened 2022-07-30 14:35 UTC by irshadCypherock

…th fails

2022-07-30 14:35 UTC, irshadCypherock commented
Task linked: [CSI-1191 BugFix: Handle case when device upgrade is successful but device auth fails on initial](https://app.clickup.com/t/37308523/CSI-1191)

2022-08-01 04:38 UTC, HarishRocks requested changes

2022-08-01 04:38 UTC, HarishRocks commented on cysync/src/pages/mainApp/deviceUpdater/initialFlow/stepperFormComponents/upgradingDevice.tsx
> +    DeviceUpgradeErrorResolutionState.DEVICE_AUTH_REQUIRED;
Wont declaring this check as a variable be a problem as its dependent on a state?  
If we're sure its not a problem, reuse it above on the `refreshComponent` function

2022-08-03 05:11 UTC, HarishRocks requested changes

2022-08-03 05:11 UTC, HarishRocks commented on cysync/src/pages/initialApp/deviceFlow/deviceSetup/stepperFormComponents/upgradingDevice.tsx
> +    } else {
Don't do this, if Cysync installs a malicious firmware and auth fails in which case the device is compromised. Cysync will move to main menu.

2022-08-04 11:55 UTC, HarishRocks commented on cysync/src/pages/initialApp/deviceFlow/deviceSetup/stepperFormComponents/upgradingDevice.tsx
> +    } else {
lets leave it as it is as we are not restricting the user if they have malicious firmware.

2022-08-04 11:55 UTC, HarishRocks approved these changes

2022-08-04 13:08 UTC, merged