CSI-1208 bugfix display gas unit and disable decimal gas values for btc forks
Cypherock/cysync-desktop pull request #171
Opened 2022-08-04 11:57 UTC by TejasvCypherock

2022-08-04 11:59 UTC, irshadCypherock commented
Task linked: [CSI-1208 Bugfix: display gas unit and disable decimal gas values for BTC forks](https://app.clickup.com/t/37308523/CSI-1208)

2022-08-05 07:42 UTC, HarishRocks commented on cysync/src/pages/mainApp/sidebar/wallet/send/formStepComponents/Recipient.tsx
> +            </Typography>
Pls amend
"sat per byte" to "sat/byte" in comm module

2022-08-05 07:55 UTC, HarishRocks requested changes

2022-08-05 07:55 UTC, HarishRocks commented on cysync/src/pages/mainApp/sidebar/wallet/send/formStepComponents/Recipient.tsx
> +          }
Pls amend "sat per byte" to "sat/byte" in comm module

2022-08-05 07:55 UTC, HarishRocks commented on cysync/src/pages/mainApp/sidebar/wallet/send/formStepComponents/Recipient.tsx
> +          }
this property of CoinData is only used on UI, so safe to change it

2022-08-05 08:02 UTC, HarishRocks requested changes

2022-08-05 08:02 UTC, HarishRocks commented on cysync/src/pages/mainApp/sidebar/wallet/send/stepperForm.tsx
> +    );
Dont do it like this
declare a new prop on CustomSlider that takes step and pass it here

2022-08-05 08:15 UTC, HarishRocks commented on cysync/src/pages/mainApp/sidebar/wallet/send/stepperForm.tsx
> +    );
we need to think of a good solution that handles input and slider fields optimally

2022-08-06 08:50 UTC, merged