feat: show derivation path on cysync
Cypherock/cysync-desktop pull request #359
Opened 2023-01-16 14:33 UTC by irshadCypherock

2023-01-16 14:33 UTC, irshadCypherock commented
Task linked: [CSI-1586 Show Derivation path on CySync](https://app.clickup.com/t/37308523/CSI-1586)

2023-01-19 12:59 UTC, TejasvCypherock requested changes

2023-01-19 12:59 UTC, TejasvCypherock commented on cysync/src/pages/mainApp/sidebar/wallet/OneCoin.tsx
> +        `Wait while we fetch the balance and latest price rates for ${coinId}`,
coinId shouldn't be shown to user

2023-01-19 13:31 UTC, TejasvCypherock approved these changes

2023-01-19 13:33 UTC, merged