Bump Bugfix: Add new API for generic gas estimation
Cypherock/cysync-desktop pull request #386
Opened 2023-02-11 00:42 UTC by TejasvCypherock

2023-02-11 00:42 UTC, rohanagarwal94 commented
Task linked: [CSI-4105 BugFix: Estimate gasLimit properly for transactions other than token transfer](https://app.clickup.com/t/9002019994/CSI-4105)

2023-02-13 11:42 UTC, irshadCypherock requested changes

2023-02-13 11:42 UTC, irshadCypherock commented on cysync/src/store/hooks/flows/useSendTransaction.ts
> +          resolve(res?.data?.fees);
Throw error if invalid data

2023-02-13 11:42 UTC, irshadCypherock commented on cysync/src/pages/mainApp/sidebar/wallet/send/stepperForm.tsx
> +    if (!token && triggeredBy !== TriggeredBy.WalletConnect) {
Can we use `!token && !txnParams?.data`

2023-02-14 10:33 UTC, merged