Bump bugfix: Wallet connect disable connection backdrop and add tooltip for amount field
Cypherock/cysync-desktop pull request #388
Opened 2023-02-14 15:10 UTC by TejasvCypherock

2023-02-14 15:10 UTC, rohanagarwal94 commented
Task linked: [CSI-4107 Bugfix: update amount field, fix Api errors, disable connection backdrop](https://app.clickup.com/t/9002019994/CSI-4107)

2023-02-15 05:10 UTC, irshadCypherock requested changes

2023-02-15 05:10 UTC, irshadCypherock commented on cysync/src/pages/mainApp/sidebar/wallet/send/formStepComponents/Recipient.tsx
> +                : ''
Also check if there is contract data present, and finalize the tooltip message

2023-02-15 05:10 UTC, irshadCypherock commented on cysync/src/pages/mainApp/sidebar/wallet/send/stepperForm.tsx
> +      )) ?? parseInt(txnParams?.gas, 16);
Add a check for undefined gas

2023-02-15 05:10 UTC, irshadCypherock commented on cysync/src/pages/mainApp/sidebar/wallet/send/stepperForm.tsx
> +          }
Allow `0` value txn on ETH

2023-02-15 05:10 UTC, irshadCypherock commented on cysync/src/store/provider/walletConnectProvider/index.tsx
> +      ipcRenderer.send('focus');
Create a handler for this event in main process

2023-02-15 07:29 UTC, irshadCypherock approved these changes

2023-02-15 07:31 UTC, merged